### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by nitishgupta4291** [hadley/rvest#166]
I get this error when i used rVest 
"This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

**Comment by hambue** [comment]
I have the same problem while using rvest in RStudio (Version 0.99.903) on Windows10 64bit.

Code example:

```
library(rvest)
lego_movie <- read_html("http://www.imdb.com/title/tt1490017/")

rating <- lego_movie %>% 
  html_nodes("strong span") 
```

Reading the html file works just fine, but RStudio stops working when _html_nodes()_ is invoked.

The error message in RStudio reads as follows:

> This application has requested the Runtime to terminate it in an unusual way.

There is no problem when using rvest in the RGui.

**Comment by cruzmiler** [comment]
Hi 

I'm observing the same error. I have a 64-bit R (3.3.1) version installed. I have been using the _html_node_ function in an application since a few months, but it suddenly stopped working and displays the same error as described in issue. 

1. I have tried reinstalling the packages _rvest_, _xml2_ and _selectr_ and RStudio (v 0.99.902) itself but the issue is unresolved. 
2. The _html_node_ function works in RGui perfectly. 

Would greatly appreciate help with this issue.

**Comment by mevalerio** [comment]
Hi,

I was using html_nodes and and read_html into a for cicle in order to read the contet of a set of webpage. 

After updating the packages used into the entire code: xml2,rvest,stringr,rJava,xlsxjars,xlsx,XLConnectJars,XLConnect the promels are arised. 

Now the routine stop each time that it arrives at 25th iteration by making fatal error and session aborted. How can I understand from where the problem come from? 
Follow an example:
for(i in 1:length(counter)) 
{
#read the content of the website
site <- paste(fair.link[i])
site <- gsub(" ","",site,fixed = TRUE)
page.html <- read_html(site)
  if (length(html_nodes(page.html,"#transcript")) == 1 ) {
  body.html <- html_nodes(page.html,"#transcript")
  body.gross < - repair_encoding(html_text(html_node(page.html,"#transcript")))
  date.gross <- html_text(html_node(page.html,"#amprestitle"))
  president.gross <- html_text(html_node(page.html,"#innercontent > h2")) 
} else {exception.l[j] <- site

j = j+1
}
}
