### ISSUE TITLE
404 error in foxnews.com

### ISSUE THREAD

**Issue by oriolmirosa** [hadley/rvest#74]
I have been using rvest to obtain references to 'global warming' from conservative websites for a research project. I had no problem doing so from, for instance, http://www.rushlimbaugh.com. However, whenever I try to get a page with ```html()``` from http://www.foxnews.com (either the homepage or any other page in the domain) I get the following error message:

```
Error in parse.response(r, parser, encoding = encoding) :
    client error: (404) Not Found
```

The webpages are clearly accessible from a browser, so I am not sure if this is a problem with rvest or if there is something specific about foxnews.com that makes this not work.

**Comment by JakeRuss** [comment]
@oriolmirosa It is easier for others to help when you include the code so that it can be copied and pasted, or some other reproducible example, just FYI. 

rvest is a wrapper for httr and httr sets the user agent for the web request, so I think that is your issue here. The user agent I get by default from httr::GET is "curl/7.35.0 Rcurl/1.95.4.5 httr/0.6.1". Some websites check the user agent before supplying their pages. Supplying a user agent with browser information makes it work for me.

    ua <- "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0"
    rvest::html("http://www.foxnews.com/", httr::user_agent(ua))

I've stuck with html() above, because html() allows for passing options to GET, but you could achieve the same result with httr alone by switching to GET directly.

    library("httr")
    GET("http://www.foxnews.com/", user_agent(ua))

**Comment by oriolmirosa** [comment]
Thanks for the help and advice, @JakeRuss, I really appreciate it. It works now.
