### ISSUE TITLE
What would be the rvest way to return an NA for a missing attribute?

### ISSUE THREAD

**Issue by JakeRuss** [hadley/rvest#77]
Here's a reproducible example that I'm working with, 
```
library("rvest")
library("magrittr")
library("stringr")

uagent <- "Mozilla/5.0"
url <- "http://web1.ncaa.org/stats/exec/records?academicYear=2015&sportCode=MBB&orgId=316"
doc <- html(url, user_agent(uagent))

# Make a list of the tables
tables <- doc %>% 
  html_nodes(xpath = "//table")
# Extract the scores table
scores <- tables[[4]] %>% 
  html_table(trim = TRUE, header = TRUE)

# Get opponent ids from the links
opp_ids <- doc %>% 
  html_nodes(xpath = "//table[2]/tr/td[1]/a") %>% 
  html_attr("href") %>% 
  str_extract_all(pattern = "[0-9]+") %>% 
  unlist()
```
Creating the `scores` object with `html_table` nets me the 32 games just as I expect. But I'd also like to scrape the links using `html_attr` because they contain opponent ids that I can extract. Notice for this example 3 teams are missing their href attribute. So my `opp_ids` end up with only 29 ids.

Ideally I'd like to stick with the rvest workflow, but will any of you suggest a way to change my `opp_ids` step such that I end up with a vector of ids that includes the three NAs?

**Comment by petermeissner** [comment]
So far -- as I know -- there is no ready made function / functionality for this - praise the one showing me that I am wrong. Therefore, I would use a workaround like this ...

    library("rvest")
    library("magrittr")
    library("stringr")
    library(httr)

    uagent <- "Mozilla/5.0"
    url <- "http://web1.ncaa.org/stats/exec/records?academicYear=2015&sportCode=MBB&orgId=316"
    doc <- html(url, user_agent(uagent))

    # Make a list of the tables
    tables <- 
      doc %>% 
      html_nodes(xpath = "//table")
    # Extract the scores table
    scores <- 
      tables[[4]] %>% 
      html_table(trim = TRUE, header = TRUE)

    # Get opponent ids from the links

    # The Extractor ... 
    extractor <- function(x){
      ifelse(
        is.null(html_node(x, xpath="a")), 
        NA,
        html_node(x, xpath="a")  %>% 
        html_attr("href") %>% 
        str_extract(pattern = "[0-9]+")
      )
    }

    # The Extraction itself
    opp_ids <- 
      doc %>% 
      html_nodes(xpath = "//td/form/table[2]/tr/td[@align='left']")   %>% 
      lapply(extractor) %>% 
      unlist()


The problem is that for 3 of the table cells there is no link meaning that they are not covered by the XPath statement and therefore you only get 29 instead of 32 links. Not, that this is no bug but only results from how XPath works (or CSS-Selectors).

My solution to problems of this kind is (we cover this  e.g. on pages 91, 398, 399, 400, 414 in [Munzert (2014)](http://www.amazon.de/Automated-Data-Collection-Practical-Scraping/dp/111883481X/ref=sr_1_5?ie=UTF8&qid=1428781399&sr=8-5&keywords=munzert) ) ...

1) to construct an XPath that returns all relevant elements as node set
2) construct an extraction function that works on the node set elements and that returns NA or the desired value depending on whether the subelement / attribute exists or not
3) to use `lapply()` to apply the extractor function to each element of the node set


One might also include step (3) in step (2) although I do not really know if this is good 'programming praxis'. Propably not but it works and everything is just in one place ... 

    # Get opponent ids from the links
    
    ## THE MIGHTY EXTRACTOR ... 
    extractor <- function(x){
      worker <- function(x){
        ifelse(
          is.null(html_node(x, xpath="a")), 
          NA,
          html_node(x, xpath="a")  %>% 
            html_attr("href") %>% 
            str_extract(pattern = "[0-9]+")
        )
      }
      unlist(lapply(x, worker))
    }
    
    # the mighty extraction
    opp_ids <- 
      doc %>% 
      html_nodes(xpath = "//td/form/table[2]/tr/td[@align='left']")   %>% 
      extractor()

**Comment by hadley** [comment]
You should be ok up to this point:

```R
opp_ids <- doc %>% 
  html_nodes(xpath = "//table[2]/tr/td[1]/a") %>% 
  html_attr("href")
```

At this point you have a vector that has NAs where the attribute is missing. 

I can't figure out what you want to do with `opps_ids %>% str_extract_all(pattern = "[0-9]+") %>% unlist()` - that's unlikely to generate a 1-to-1 mapping between input and output. What do you want to return if there is more than one match? 

This problem seems out of the scope of httr - you basically need to switch from an approach that's equivalent to `lapply()` + `unlist()` to one that's equivalent to `vapply()`. `unlist()` + `lapply()` is a dangerous pattern for scraping, and best avoided.

**Comment by JakeRuss** [comment]
I'm having trouble seeing the NAs where the attribute is missing
```
# Get opponent ids from the links
opp_ids <- doc %>% 
  html_nodes(xpath = "//td/form/table[2]/tr/td/a") %>% 
  html_attr("href")
```
When I run this step I get the 29 links but without the NAs being in the resulting vector.

**Comment by hadley** [comment]
Oh you might need to do something that combines `html_nodes` and `html_node`.

**Comment by AzamYahya** [comment]
@hadley can you please give a reproducible example to combine `html_nodes` and `html_node` that can replace the missing attributes with NA.
